### ISSUE TITLE
1.21 Tracking

### ISSUE THREAD

**Issue by Notenoughmail** [Notenoughmail/KubeJS-TFC#9]
- TFC
  - [x] Food traits are now a proper registry
  - [ ] Food data has had some changes
  - [x] Block ingredients are rather simplified
  - [x] Fluid (stack) ingredients are now part of Neo
  - [x] DelegateIngredient is dead, long live PreciseIngredient
  - [x] ISM(T)s are a proper registry
  - [x] ISPs are now codec'd, modifiers are now a list
  - [x] Data managers are now a registry ???
  - [x] A lot of data manager values have been turned into codec'd records --> data event easier?
  - [x] Metal ingot/double ingot are now under a IngredientParts sub-object
  - [x] Climate model (type)s now require a stream codec and are a proper registry
  - [ ] Pot output types are now a proper registry
  - [x] TFCDirt's mud and rooted suppliers are no longer nullable
  - [x] Delegate recipe types are now ISMs
  - [ ] TFCFoodData and PlayerData are now merged into PlayerInfo
  - [x] Bar registry?
  - [x] Javelin model changes [again](https://github.com/TerraFirmaCraft/TerraFirmaCraft/compare/64ffcc56ae00...009f1c698498#diff-e9b03c93ea06ff1709b05d0abd90f58bfdd11431edb080e6d897963841ea5a4bR913-R914)
  - [x] RawRockBlock no longer takes a boolean and a Component
  - [ ] AnimalProperties now part of SynchedEntityData
  - [x] Many (most? all?) places now take a `Supplier<`type`>` instead of a config object
  - [x] InteractionManager targeting refactor
  - [x] KeyedIngredient
  - [ ] Biome extensions are now a proper registry
    - [ ] May have to hack the registry's backing array if scriptors add too many custom extensions
  - [ ] Soil Discs are Metaballs now
  - [x] WaterWheel textures are now gotten from a static map instead of the block itself
  - [x] Item model loader `tfc:contained_fluid` -> `tfc:fluid_container`
  - [x] `ContainedFluidModel` color handler is now a static object, instead of initialized for every item
  - [x] `ChiselMode` is now a registry, modes have several overrideable methods
  - [x] Placed items can now have special placed models, see `PlacedItemBlockEntityRenderer#MODELS`
  - [x] Fairly major climate model refactoring
    - [ ] Wanted change for kjstfc: custom models extend overworld model and replace/augment super
value
    - [x] CMTs are now a stream codec, allow custom? or just copy the default's?
    - [x] Hemisphere scale 
    - [x] Faunas can now be restricted by month
  - [x] Glass operations are a registry
- Kube
  - [ ] A whole lot
  - [ ] Records are now automatically wrapped
  - [ ] Type info registering
- Neo/MC
  - [ ] Now has an event for hacking BEs
  - [ ] `(neo)forge:contained_fluid` -> `neoforge:fluid_container`
  - [ ] The attachment refactor

**Comment by wuming123** [comment]
I can't wait to use this in 1.21.1

**Comment by Notenoughmail** [comment]
KubeJS TFC 2.0.0 for 1.21.1 has been released, obsoleting this issue. Report any encountered issues in the usual place :)
